version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3301:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d  #初期データ
    environment:
      MYSQL_DATABASE: duo
      MYSQL_ROOT_PASSWORD: root
    container_name: duo_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci